# This workflow will install Python dependencies, run tests and lint with different versions of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# As github support for Python2.7 has gone to meet its maker, we cannot
# run successful coverage tests here.

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 23 * * 1'  # run once a week on Monday
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (3.9)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: |
          tox run -e 'lint,py39'
