# This workflow will install Python dependencies, run tests and lint with different versions of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 23 * * 1'  # run once a week on Monday
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        config:
          #- [ "2.7", "py27"]
          #- [ "3.5", "py35"]
          #- [ "3.6", "py36"]
          #- [ "3.7", "py37"]
          #- [ "3.8", "py38"]
          - [ "3.9", "lint,clean,py27,py39,report"]
          #- [ "pypy-2.7", "pypy"]
          #- [ "pypy-3.7", "pypy3"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.config[0] }}
        uses: actions/setup-python@v5
        with:
          python-version: |
              "2.7"
              ${{ matrix.config[0] }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: |
          tox -e ${{ matrix.config[1] }}
